public class Hello {
    public static void main(String[] args) {
        System.out.println("Hello, World!");
        int num1 = 3;
        int num2 = 5;
        int result = num1 + num2;
        System.out.println(num1 + " + " + num2 + " = " + result);
        byte byteValue = 100;
        short shortValue = 127;
        long longValue = 5854L;
        float floatValue = 3.14f;
        double doubleValue = 3.141592653589793;
        char charValue = 'A';
        boolean booleanValue = true;
        System.out.println("Byte value: " + byteValue);
        System.out.println("Short value: " + shortValue);
        System.out.println("Long value: " + longValue);
        System.out.println("Float value: " + floatValue);
        System.out.println("Double value: " + doubleValue);
        System.out.println("Char value: " + charValue);
        System.out.println("Boolean value: " + booleanValue);
        int binaryValue = 0b101;
        System.out.println("Binary value (0b101): " + binaryValue);
        int hexValue = 0x7e;
        System.out.println("Hexadecimal value (0x7e): " + hexValue);
        byte b = 127;
        System.out.println("Byte value: " + b);
        int a = b;
        System.out.println("Int value (after widening): " + a);
        int k = 257;
        byte c = (byte) k;
        System.out.println("Byte value (after narrowing): " + c);
        float f = 5.6f;
        int t = (int) f;
        System.out.println("Int value (after narrowing from float): " + t);
        byte b1 = 10;
        byte b2 = 30;
        int b3 = b1 * b2;
        System.out.println("Result of byte multiplication (b1 * b2): " + b3);
        num1 = 7;
        num2 = 5;
        int res = num1 + num2;
        System.out.println(num1 + " + " + num2 + " = " + res);
        res = num1 - num2;
        System.out.println(num1 + " - " + num2 + " = " + res);
        res = num1 * num2;
        System.out.println(num1 + " * " + num2 + " = " + res);
        res = num1 / num2;
        System.out.println(num1 + " / " + num2 + " = " + res);
        res = num1 % num2;
        System.out.println(num1 + " % " + num2 + " = " + res);
        num1 += 2;
        System.out.println("After num1 += 2: " + num1);
        num2 *= 3;
        System.out.println("After num2 *= 3: " + num2);
        num2 -= 4;
        System.out.println("After num2 -= 4: " + num2);
        num2 /= 2;
        System.out.println("After num2 /= 2: " + num2);
        num1 %= 3;
        System.out.println("After num1 %= 3: " + num1);
        num1++;
        System.out.println("After num1++: " + num1);
        num2--;
        System.out.println("After num2--: " + num2);
    }
}
